#!/bin/sh

mount -t sysfs sysfs /sys
mount -t proc proc /proc
mount -t devtmpfs udev /dev

clear
# resolve "can't access tty; job control turned off"
setsid sh -c 'exec sh </dev/tty1 >/dev/tty1 2>&1'
poweroff -f
